import { ApolloWrapper } from '@/app/ApolloWrapper'
import { Header } from '@/app/components/Header'
import { Footer } from '@/app/components/Footer'


import 'app/globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ApolloWrapper>
        <Header/>
          {children}
        <Footer/>
      </ApolloWrapper>
      </body>
    </html>
)
}
